### ISSUE TITLE
Colors not showing... ideas?

### ISSUE THREAD

**Issue by danielnjoo** [fuzhenn/node-svg2img#7]
[Desired image](https://imgur.com/a/UGwEA)
[Output image](https://imgur.com/a/UGwEA)

The SVG string renders in codepen as desired, however, when I render it with svg2img I get the output as above. Any ideas where this might be going wrong?

My pipeline involves posting the rendered JPEG to s3, and then sending it via Facebook Messenger, and it hasn't gone wrong until now.

If you need any more info let me know, thanks for any help :)!

**Comment by fuzhenn** [comment]
Hi!

svg2img‘s work flow is as below:

img => svg2img(prepare options) => canvg(parse SVG and draw on canvas) => node-canvas

The problem looks like a parsing problem of [canvg](https://github.com/canvg/canvg). If it's OK, you can post your SVG here, I will take a quick check if there is anything unnormal.

**Comment by danielnjoo** [comment]
[Here's](https://codepen.io/danielnjoo/pen/gXmONN) the svgstring, amazing response time 👍

**Comment by fuzhenn** [comment]
Sorry for the late response.

It may be related with external css.

```css
        .axis {
          stroke: #555;
          stroke-width: .2;
        }
        .scale {
          fill: #e7e7e7;
          stroke: #999999;
          stroke-width: .2;
        }
        .shape {
          fill-opacity: .7;
          stroke-width: .5;
        }
        .shape:hover {
          fill-opacity: .6;
        }
        
    .shape.something1 { fill: #edc951; }
    .shape.something2  { fill: #cc333f; }
    .shape.something3 { fill: #00a0b0; }
```

canvg doesn't support style defines in external CSS, as https://github.com/canvg/canvg/issues/323. You can try to inline the styles, it may resolve your problem.
